### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [yeseg11/Let-it-know#10]
- חסר שונות בין חברי הצוות
- עבודה יפה

**Comment by Oterem** [comment]
תודה קובי. לא ברור לי באיזה חלק אמור להופיע השונות...נדרשנו לכך בדף הצוות ורשמנו את זה:
https://github.com/yeseg11/Let-it-know/wiki/Team#team-diversity
@kob-e

**Comment by YaakovHatam** [comment]
@Oterem  אין לכם עוד מה להוסיף על השונות בין חברי הצוות?

**Comment by yeseg11** [comment]
סבבה, נתקן ונוסיף תודה

**Comment by yeseg11** [comment]
@kob-e 
 הוספנו שאנו שאנחנו באים מרקעים שונים אבל קיבלנו הוראה מראובן לא לפרט יותר מידי .

**Comment by YaakovHatam** [comment]
אוקיי, עבודה יפה.

**Comment by yeseg11** [comment]
@kob-e 
היי תיקנו את שונות הקבוצה והוספנו במה אנחנו שונים ומיוחדים.
נתת לנו 90 על השונות אשמח לדעת אם זה בסדר ואפשר לתקן את זה ?
