### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [yeseg11/Let-it-know#19]
## TODO:
- Please attach here the Client review.

## סיכום פגישתנו:
רעיון נחמד, צריך למצוא עוד סיכונים, משימה ברורה מצד הלקוח.

**Comment by yeseg11** [comment]
@kob-e 
הוספנו סיכונים, אשמח להבין מה חסר עם הוספת המידע מהלקוח. 
בנוסף נראה לי שהתכוונת לתיקון ב
Project Inception
https://github.com/yeseg11/Let-it-know/wiki/Project-Inception

**Comment by kob-e** [comment]
אוקיי, עבודה יפה.

**Comment by YaakovHatam** [comment]
@yeseg11 צריך לקבל פידבק מהלקוח לגבי התהליך, מייל סיכום אמצע או תמלול פגישה.
לגבי הסיכונים, זה מה שדיברנו בכיתה בפגישה כתבתי את התמצית.

**Comment by yeseg11** [comment]
@avicohen89 
מעלה את התמלול שיחה שעשינו עם נדב 
לפה https://github.com/yeseg11/Let-it-know/wiki/Project-Inception

**Comment by yeseg11** [comment]
@kob-e  
הועלה סיכום הפגישה עם הלקוח :-)

**Comment by YaakovHatam** [comment]
יפה מאוד!

**Comment by yeseg11** [comment]
ראינו שהורדת ציון ב
Risks:
מנינו מספר סיכונים , הכנסו את כל המידע איך לטפל בהם ואת חשיבותם. 
הגדלנו לעשות ובדקנו אצל צוותים מקבילים ע"מ לבדוק את טעותנו, ללמוד ולתקן בהתאם לפני פניה זו , אך לא הבחנו בשוני יוצא דופן בין המסמכים. 

Review : 
תיקנו והוספנו.

**Comment by yeseg11** [comment]
@kob-e
