### ISSUE TITLE
Mission 4 - SDS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [yeseg11/Let-it-know#24]

**Comment by yeseg11** [comment]
אפשרי לסגור את זה ?

**Comment by yeseg11** [comment]
@kob-e

**Comment by yeseg11** [comment]
@kob-e 

SDS Page : 
אשמח לדעת על מה ירדו 5 נקודות ? 
UML:
הועלה תרשים נוסף של uml 
Sections:
לא ברור על מה ירדו פה נקודות, עברנו על דפים שקיבלו ציון 100 ואנחנו לא רואים שינוי 
Update & Summary: 
עודכן
